In [1]:
import numpy as np
from numpy import linalg as la

In [2]:
r=64.
x=np.array([7,4,6,8,8,7,5,9,7,8])
y=np.array([4,1,3,6,5,2,3,5,4,2])
z=np.array([3,8,5,1,7,9,3,8,5,2])
data = np.array([x, y,z])
print(data)
xMean = np.mean(x)
yMean = np.mean(y)
zMean = np.mean(z)
print(xMean)
print(yMean)
print(zMean)

[[7 4 6 8 8 7 5 9 7 8]
 [4 1 3 6 5 2 3 5 4 2]
 [3 8 5 1 7 9 3 8 5 2]]
6.9
3.5
5.1


In [3]:
meanAdjusted = np.zeros((3, 10))
for i in range(len(data[0])):
    meanAdjusted[0][i] = data[0][i] - xMean
for i in range(len(data[1])):
    meanAdjusted[1][i] = data[1][i] - yMean
for i in range(len(data[2])):
    meanAdjusted[2][i] = data[2][i] - zMean
print(meanAdjusted)

[[ 0.1 -2.9 -0.9  1.1  1.1  0.1 -1.9  2.1  0.1  1.1]
 [ 0.5 -2.5 -0.5  2.5  1.5 -1.5 -0.5  1.5  0.5 -1.5]
 [-2.1  2.9 -0.1 -4.1  1.9  3.9 -2.1  2.9 -0.1 -3.1]]


In [4]:
cov_mat = np.cov(data)
print(cov_mat)
eig_vals, eig_vecs = np.linalg.eig(cov_mat)
print('Eigenvectors \n%s' %eig_vecs)
print('\nEigenvalues \n%s' %eig_vals)

[[ 2.32222222  1.61111111 -0.43333333]
 [ 1.61111111  2.5        -1.27777778]
 [-0.43333333 -1.27777778  7.87777778]]
Eigenvectors 
[[-0.70172743  0.69903712 -0.1375708 ]
 [ 0.70745703  0.66088917 -0.25045969]
 [ 0.08416157  0.27307986  0.95830278]]

Eigenvalues 
[0.74992815 3.67612927 8.27394258]


In [5]:
eig_pairs = [(np.abs(eig_vals[i]), eig_vecs[:,i]) for i in range(len(eig_vals))]

In [6]:
eig_pairs.sort()
eig_pairs.reverse()

In [7]:
print('Eigenvalues in descending order:')
for i in eig_pairs:
    print(i[0])

Eigenvalues in descending order:
8.273942580407862
3.676129266797332
0.7499281527948032


In [8]:
print('Eigenvectors in descending order:')
for i in eig_pairs:
    print(i[1])

Eigenvectors in descending order:
[-0.1375708  -0.25045969  0.95830278]
[0.69903712 0.66088917 0.27307986]
[-0.70172743  0.70745703  0.08416157]


In [9]:
eig_pairs[0][1]

array([-0.1375708 , -0.25045969,  0.95830278])

In [10]:
transformedData1 = np.matmul(meanAdjusted.T, eig_pairs[0][1])
transformedData2 = np.matmul(meanAdjusted.T, eig_pairs[1][1])
transformedData3 = np.matmul(meanAdjusted.T, eig_pairs[2][1])
transformedData =[transformedData1,transformedData2,transformedData3]
transformedData =np.transpose(transformedData)
print(transformedData)

[[-2.15142276 -0.17311941  0.10681648]
 [ 3.80418259 -2.88749898  0.5104355 ]
 [ 0.15321328 -0.98688598  0.26941001]
 [-4.7065185   1.30153634  0.65167999]
 [ 1.29375788  2.27912632  0.44919235]
 [ 4.0993133   0.1435814  -0.80312818]
 [-1.62582148 -2.23208282  0.80281431]
 [ 2.11448986  3.2512433  -0.16837351]
 [-0.2348172   0.37304031  0.27513962]
 [-2.74637697 -1.06894049 -2.09398657]]
